# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 20:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170818_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Wrong format. Phone must be only numbers, and between 8-15 characters. Example: 12345678', regex='^\\d{8,15}$')]),
        ),
    ]
