# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 16:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170818_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Wrong format. Example: 12345678', regex='^\\d{8,15}$')]),
        ),
    ]
