# Generated by Django 2.1.8 on 2019-04-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190401_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.CharField(max_length=10),
        ),
    ]
