# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170821_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreview',
            name='review',
            field=models.CharField(default='', max_length=280),
            preserve_default=False,
        ),
    ]
