# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.URLField(blank=True, max_length=140, null=True),
        ),
    ]
