# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_project_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='big',
            field=models.BooleanField(default=False),
        ),
    ]
