# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_projectimage_big'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['hierarchy']},
        ),
        migrations.AddField(
            model_name='projectimage',
            name='hierarchy',
            field=models.IntegerField(default=0),
        ),
    ]
