# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20170823_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='abstract',
            field=models.CharField(max_length=240),
        ),
    ]
