# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20171020_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='abstract',
            field=models.CharField(max_length=280),
        ),
    ]
