# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-13 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20171020_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='ux_ui',
            new_name='hardware',
        ),
    ]
